In [1]:
import numpy as np

In [5]:
mylist = np.array([1,2,3])

In [6]:
np.max(mylist)

np.int64(3)

# Array Arithmetic

In [9]:
myList1 = [1,2]
myList2 = [2,3]

myNumpyArray1 = np.array(myList1)
myNumpyArray2 = np.array(myList2)

myNumpyArray1 + myNumpyArray2

array([3, 5])

In [10]:
myNumpyArray2 * 5

array([10, 15])

In [11]:
otherArray = np.array([1,2,3])
otherArray.min()

np.int64(1)

In [12]:
otherArray.sum()

np.int64(6)

# Arange and Indexing

In [17]:
np.arange(0,10)
np.arange(0,10,4)

array([0, 4, 8])

In [19]:
npArray = np.arange(0,10)
npArray[1:4:]
npArray[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
np.random.rand()

0.6799288506321963

# Matrices

In [26]:
npMatrix = np.array([[1,2,3],[4,5,6]])
npMatrix


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
npMatrix[0,0]

np.int64(1)

In [29]:
npMatrix.sum()

np.int64(21)

In [30]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.random.random((3,12))

array([[0.15430214, 0.67727129, 0.85250936, 0.13107425, 0.58896208,
        0.50553218, 0.90743947, 0.83996654, 0.62604274, 0.81895645,
        0.68619214, 0.49166676],
       [0.09153718, 0.88628159, 0.59510766, 0.59438872, 0.25231374,
        0.78421105, 0.7846082 , 0.27663885, 0.11042745, 0.17417943,
        0.13696281, 0.73256221],
       [0.42077491, 0.31838558, 0.52894068, 0.78208932, 0.27091715,
        0.89034003, 0.87382341, 0.04571041, 0.30391599, 0.12548497,
        0.57851046, 0.2527713 ]])

# Matrix Arithmetic


In [41]:
firstMatrisx = np.array([[1,2,3],[4,5,6]])
secondMatrix = np.array([[1,2],[4,5],[6,1]])

In [42]:
firstMatrisx + secondMatrix

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

# Matrix Multiplication

In [43]:
firstMatrisx * secondMatrix

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [44]:
firstMatrisx.shape

(2, 3)

In [45]:
secondMatrix.shape

(3, 2)

In [48]:
resultMatrix = firstMatrisx.dot(secondMatrix)
resultMatrix

array([[27, 15],
       [60, 39]])